image: debian:latest

before_script:
  - apt-get update
  - apt-get install -y gcc make zlib1g-dev libhts-dev git
  - git clone https://evolgen:${CI_JOB_TOKEN}@gitlab.com/evolgen/libplink_lite.git
  - cd libplink_lite
  - make
  - make install
  - cd ..
  - git clone https://evolgen:${CI_JOB_TOKEN}@gitlab.com/evolgen/libpbwt.git
  - cd libpbwt
  - make
  - make install
  - cd ..

build:
  stage: build
  script:
    - make
    - ./pbwtmaster summary /libpbwt/test/HumanOriginsExample.pbwt 0.5 200 0 729
  only:
    - tags